In [1]:
array = [10,23,32,32,3,32,3,22323,23]
array


[10, 23, 32, 32, 3, 32, 3, 22323, 23]

In [4]:
import numpy as np
# converting a list as numpy array 
numpy_array1 = np.array(array)
numpy_array1 
# this can be  extracted from the o/p

array([   10,    23,    32,    32,     3,    32,     3, 22323,    23])

In [6]:
# numpy array can contain only one type of the element while the list in the python consists of the different types of data types ::::: 

In [12]:
list_x = list(range(1000000))
list_y = list(range(1000000))
array_x= np.array(list_x)
array_y= np.array(list_y)
def list_sum():
    z=[] # a list to store the sum of list 1 and 2 
    for i in range(len(list_x)):
        z.append(list_x[i]+list_y[i])
    return z


In [16]:
def numpy_array_sum():
    z= array_x+ array_y
# print(z)
numpy_array_sum()

In [23]:
x=[]
for i in range(11):
    if i%2==0:
        x.append(i)
x
# putting it to the np.array 
x_array= np.array(x)
x_array

[0, 2, 4, 6, 8, 10]

In [27]:
#  making directly form the numpy 
x12=np.arange(0,10,2)
x12

array([0, 2, 4, 6, 8])

In [29]:
# selecting all the odds is to easy 
x11= np.arange(1,10,2)
x11

array([1, 3, 5, 7, 9])

In [30]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.size

9

In [32]:
arr.dtype

dtype('int32')

In [33]:
arr.shape

(3, 3)

In [34]:
# arr.ndim for the number of dimensions 
arr.ndim

2

In [35]:
type(arr)

numpy.ndarray

In [37]:
# dtype method is not supported by the lists in the python 
x1=np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# the higher limit is excluded out of the array
x1=np.arange(5,10)
x1

array([5, 6, 7, 8, 9])

In [40]:
x1=np.arange(10,20,3)
x1

array([10, 13, 16, 19])

In [42]:
#  using the zeroes 
x2 = np.zeros(5)
x2

array([0., 0., 0., 0., 0.])

In [46]:
x2=np.ones(4)
x2

array([1., 1., 1., 1.])

In [49]:
# linespace() generates the values equally spaaced
# num is the number of values you want to generate 
# bydefault it is set to be 50 
x2= np.linspace(start =5,stop=10,num=5)
x2
x2= np.linspace(start=1,stop=2)
x2

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [50]:
x3= np.linspace(start=17,stop=31)
x3

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [52]:
k=np.zeros(10)
k

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
k.ndim

1

In [61]:
# it have appended four times as it seems to be we have actually declared and used it more times than we did 
k=np.append(k,34)
k

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 34., 34., 34.,
       34., 34., 34.])

In [63]:
# k.append(20) not supported by the numpy array 

In [64]:
#  deletin  the element from the specific pos 
np.delete(k,10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 34., 34., 34.,
       34., 34.])

In [66]:
np.sort(k)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 34., 34., 34.,
       34., 34., 34.])

In [69]:
k=np.append(k,-909)
k

array([   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,   34.,   34.,   34.,   34.,   34.,   34., -909.])

In [70]:
np.sort(k)

array([-909.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,   34.,   34.,   34.,   34.,   34.,   34.])

In [71]:
# Reshaping the array 


In [72]:
x4= np.arange(24)
x4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
x4=np.reshape(x4,(8,3))
x4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [76]:
x4=np.reshape(x4,(4,6))
x4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [78]:
# Python list can also be reshaped 
x5=[122,232,3,24,43,4,34,3,43,3,2,43,34,3,34,3,3,4]
x5.count(3)

6

In [81]:
x5=np.reshape(x5,(3,6))
x5

array([[122, 232,   3,  24,  43,   4],
       [ 34,   3,  43,   3,   2,  43],
       [ 34,   3,  34,   3,   3,   4]])

In [82]:
#  the list must be of the type npArray
x5.reshape(6,3)

array([[122, 232,   3],
       [ 24,  43,   4],
       [ 34,   3,  43],
       [  3,   2,  43],
       [ 34,   3,  34],
       [  3,   3,   4]])

In [83]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]
L=np.array(L)
L=np.sort(L)
L

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [84]:
type(L)

numpy.ndarray

In [85]:
L=np.delete(L,5)
L

array([ 2,  3,  7,  8, 10, 13, 22, 23, 25, 41, 46, 54])

In [86]:
x6=x5.reshape(6,3)
x6

array([[122, 232,   3],
       [ 24,  43,   4],
       [ 34,   3,  43],
       [  3,   2,  43],
       [ 34,   3,  34],
       [  3,   3,   4]])

In [87]:
x6[5]

array([3, 3, 4])

In [88]:
x6[3][2]

43

In [89]:
x6[3,2]

43

In [90]:
x6[0,0:2]

array([122, 232])

In [91]:
x6[4,:]
# bydefault it takes the first and the last value 

array([34,  3, 34])

In [92]:
x6[:,:]

array([[122, 232,   3],
       [ 24,  43,   4],
       [ 34,   3,  43],
       [  3,   2,  43],
       [ 34,   3,  34],
       [  3,   3,   4]])

In [94]:
x6[1:4,1:]

array([[43,  4],
       [ 3, 43],
       [ 2, 43]])

In [96]:
x6[:,1:2]

array([[232],
       [ 43],
       [  3],
       [  2],
       [  3],
       [  3]])

In [97]:
# negetive indexing 
x6[-1]

array([3, 3, 4])

In [101]:
x6[-4:-2,-2:]

array([[ 3, 43],
       [ 2, 43]])

In [103]:
# striding 
x6[0::2]
# this will print the every secondth row from the beginning 

array([[122, 232,   3],
       [ 34,   3,  43],
       [ 34,   3,  34]])

In [105]:
x7=np.arange(25)
x7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [107]:
x7=np.reshape(x7,(5,5))
x7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
x7[1::2,0::2]

array([[ 5,  7,  9],
       [15, 17, 19]])

In [117]:
# addition within the space given 
xx=np.arange(10)
yy=np.arange(10)
zz=[xx + yy for i in range(len(xx))]

In [120]:
x7=np.append(x7,25)
x7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 23, 25])

In [121]:
# creating a 3d array 
x7=np.reshape(x7,(3,3,3))
x7

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 23, 25]]])

In [123]:
x8=np.full((5,6),3)
x8

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [131]:
# flatten() and ravel()

In [136]:
x9=np.arange(10)
x9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.sin(x9)
# array must be one dimension 

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [138]:
np.sqrt(x9)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [139]:
np.logical_or(x9<1,x9>3)

array([ True, False, False, False,  True,  True,  True,  True,  True,
        True])

In [140]:
np.logical_and(x9<1,x9>3)

array([False, False, False, False, False, False, False, False, False,
       False])

In [141]:
np.array_equal(x9,x8)

False

In [ ]:
# https://github.com/dphi-official/Data_Science_Bootcamp/tree/master/Week0
# https://github.com/dphi-official/Data_Science_Bootcamp/blob/master/Week0/Numpy_Exercises_Solutions.ipynb